# Generated by Django 5.2.4 on 2025-07-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image to send with the message', null=True, upload_to='scheduled_messages/images/', verbose_name='Optional Image'),
        ),
    ]
