# Generated by Django 5.2.4 on 2025-08-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_scheduler', '0002_scheduledmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='video',
            field=models.FileField(blank=True, help_text='Optional video to send with the message', null=True, upload_to='scheduled_messages/videos/', verbose_name='Optional Video'),
        ),
    ]
