# Generated by Django 5.2.4 on 2025-08-17 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_phone_number'),
        ('notifications_scheduler', '0003_scheduledmessage_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='notifications_scheduler.errortype')),
            ],
        ),
        migrations.CreateModel(
            name='ClientScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent Date and Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='clients.client')),
                ('scheduled_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_messages', to='notifications_scheduler.scheduledmessage')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_message', to='notifications_scheduler.messageresponse')),
            ],
            options={
                'verbose_name': 'Client Message',
                'verbose_name_plural': 'Client Messages',
            },
        ),
        migrations.DeleteModel(
            name='ClientMessage',
        ),
        migrations.AddConstraint(
            model_name='clientscheduledmessage',
            constraint=models.UniqueConstraint(fields=('scheduled_message', 'client'), name='unique_scheduled_message_per_client'),
        ),
    ]
