# Generated by Django 5.2.4 on 2025-08-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_scheduler', '0004_errortype_messageresponse_clientscheduledmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientscheduledmessage',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientscheduledmessage',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='clientscheduledmessage',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='errortype',
            name='retryable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='code',
            field=models.CharField(choices=[('NETWORK', 'NETWORK'), ('BLOCKED', 'BLOCKED'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('TIMEOUT', 'TIMEOUT'), ('RATE_LIMIT', 'RATE_LIMIT'), ('UNKNOWN', 'UNKNOWN'), ('EXCEPTION', 'EXCEPTION')], max_length=50, unique=True),
        ),
    ]
