# Generated by Django 5.2.4 on 2025-08-18 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_scheduler', '0005_clientscheduledmessage_last_retry_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientscheduledmessage',
            name='response',
        ),
        migrations.AddField(
            model_name='messageresponse',
            name='client_message',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='notifications_scheduler.clientscheduledmessage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='errortype',
            name='code',
            field=models.CharField(choices=[('NETWORK', 'NETWORK'), ('BLOCKED', 'BLOCKED'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('TIMEOUT', 'TIMEOUT'), ('RATE_LIMIT', 'RATE_LIMIT'), ('UNKNOWN', 'UNKNOWN'), ('NO_INPUT_BOX', 'NO_INPUT_BOX'), ('WHATSAPP_DOWN', 'WHATSAPP_DOWN'), ('EXCEPTION', 'EXCEPTION')], max_length=50, unique=True),
        ),
    ]
