# Generated by Django 5.2.4 on 2025-08-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_scheduler', '0006_remove_clientscheduledmessage_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageresponse',
            name='error_type',
        ),
        migrations.AddField(
            model_name='messageresponse',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messageresponse',
            name='response_code',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('NETWORK', 'NETWORK'), ('BLOCKED', 'BLOCKED'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('TIMEOUT', 'TIMEOUT'), ('RATE_LIMIT', 'RATE_LIMIT'), ('UNKNOWN', 'UNKNOWN'), ('NO_INPUT_BOX', 'NO_INPUT_BOX'), ('WHATSAPP_DOWN', 'WHATSAPP_DOWN'), ('EXCEPTION', 'EXCEPTION')], default='WHATSAPP_DOWN', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messageresponse',
            name='retryable',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ErrorType',
        ),
    ]
