# Generated by Django 5.2.4 on 2025-08-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_scheduler', '0007_remove_messageresponse_error_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageresponse',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='messageresponse',
            name='response_code',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'SUCCESS'), ('NETWORK', 'NETWORK'), ('BLOCKED', 'BLOCKED'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('TIMEOUT', 'TIMEOUT'), ('RATE_LIMIT', 'RATE_LIMIT'), ('UNKNOWN', 'UNKNOWN'), ('NO_INPUT_BOX', 'NO_INPUT_BOX'), ('WHATSAPP_DOWN', 'WHATSAPP_DOWN'), ('EXCEPTION', 'EXCEPTION')], max_length=50, null=True),
        ),
    ]
