# Generated by Django 5.2.4 on 2025-08-31 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_scheduler', '0008_alter_messageresponse_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientscheduledmessage',
            options={'verbose_name': 'Client Scheduled Message', 'verbose_name_plural': 'Client Scheduled Messages'},
        ),
        migrations.CreateModel(
            name='ClientScheduledMessageImportErrorLog',
            fields=[
                ('importerrorlog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications_scheduler.importerrorlog')),
                ('client_scheduled_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_errors', to='notifications_scheduler.clientscheduledmessage')),
            ],
            bases=('notifications_scheduler.importerrorlog',),
        ),
    ]
