# Generated by Django 5.2.4 on 2025-09-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_scheduler', '0009_importerrorlog_alter_clientscheduledmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='client_type',
            field=models.CharField(blank=True, choices=[('prospect', 'Prospect'), ('consolidated', 'Consolidated'), ('inactive', 'Inactiv'), ('vip', 'VIP')], default='consolidated', help_text='Tipo de cliente al momento de enviar la notificación.', max_length=20),
        ),
    ]
