# Generated by Django 5.2.4 on 2025-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_scheduler', '0010_scheduledmessage_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='auto_generate_clients',
            field=models.BooleanField(default=False, help_text='Si está activo, al guardar se generarán ClientScheduledMessages para todos los clientes del tipo seleccionado y sus MessageResponses.'),
        ),
        migrations.AlterField(
            model_name='messageresponse',
            name='response_code',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'SUCCESS'), ('NETWORK', 'NETWORK'), ('BLOCKED', 'BLOCKED'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('NOT_FOUND_IN_WHATSAPP', 'NOT_FOUND_IN_WHATSAPP'), ('TIMEOUT', 'TIMEOUT'), ('RATE_LIMIT', 'RATE_LIMIT'), ('UNKNOWN', 'UNKNOWN'), ('NO_INPUT_BOX', 'NO_INPUT_BOX'), ('WHATSAPP_DOWN', 'WHATSAPP_DOWN'), ('EXCEPTION', 'EXCEPTION')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='client_type',
            field=models.CharField(blank=True, choices=[('prospect', 'Prospect'), ('consolidated', 'Consolidated'), ('inactive', 'Inactiv'), ('imported', 'Imported'), ('vip', 'VIP')], default='consolidated', help_text='Tipo de cliente al momento de enviar la notificación.', max_length=20),
        ),
    ]
