# Generated by Django 5.2.4 on 2025-11-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_scheduler', '0011_scheduledmessage_auto_generate_clients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='auto_generate_clients',
        ),
        migrations.AddField(
            model_name='clientscheduledmessage',
            name='force_pending_on_update',
            field=models.BooleanField(default=False, help_text='¿Desea actualizar el estado del mensaje programado a pendiente?', verbose_name='Force MessageResponse to pending on update'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='auto_generate_client_scheduled_messages',
            field=models.BooleanField(default=False, help_text='Si está activo, al guardar se generarán/actualizarán ClientScheduledMessages para todos los clientes del tipo seleccionado y sus MessageResponses.', verbose_name='Auto generate client scheduled messages'),
        ),
    ]
