# Generated by Django 5.2.4 on 2025-11-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_scheduler', '0012_remove_scheduledmessage_auto_generate_clients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientscheduledmessage',
            name='force_pending_on_update',
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='force_pending_on_update',
            field=models.BooleanField(default=False, help_text='¿Desea actualizar el estado del mensaje programado a pendiente?', verbose_name='Force MessageResponse to pending on update'),
        ),
    ]
