# Generated by Django 5.2.4 on 2025-12-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_scheduler', '0013_remove_clientscheduledmessage_force_pending_on_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='replace_text_message_variables',
            field=models.BooleanField(default=False, help_text='Si está activo, se reemplazarán las variables en el texto del mensaje antes de enviarlo.', verbose_name='Replace Text Message Variables'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='scheduled_message_type',
            field=models.CharField(choices=[('PROMOTIONAL', 'Promocional'), ('REMINDER', 'Recordatorio'), ('ALERT', 'Alerta'), ('FOLLOWUP', 'Seguimiento'), ('BIRTHDAY', 'Cumpleaños'), ('CUSTOM', 'Personalizado')], default='CUSTOM', max_length=20, verbose_name='Scheduled Message Type'),
        ),
        migrations.AlterField(
            model_name='messageresponse',
            name='response_code',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'SUCCESS'), ('NETWORK', 'NETWORK'), ('BLOCKED', 'BLOCKED'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('NOT_FOUND_IN_WHATSAPP', 'NOT_FOUND_IN_WHATSAPP'), ('TIMEOUT', 'TIMEOUT'), ('RATE_LIMIT', 'RATE_LIMIT'), ('UNKNOWN', 'UNKNOWN'), ('NO_INPUT_BOX', 'NO_INPUT_BOX'), ('WHATSAPP_DOWN', 'WHATSAPP_DOWN'), ('WHATSAPP_SESSION_CRASHED', 'WHATSAPP_SESSION_CRASHED'), ('UPLOAD_MEDIA_FAILED', 'UPLOAD_MEDIA_FAILED'), ('EXCEPTION', 'EXCEPTION')], max_length=50, null=True),
        ),
    ]
