# Generated by Django 5.2.4 on 2025-08-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='area_code',
            field=models.CharField(default='57', max_length=5),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('consolidated', 'Consolidated'), ('inactive', 'Inactiv'), ('vip', 'VIP')], default='prospect', max_length=20),
        ),
    ]
