# Generated by Django 5.2.4 on 2025-08-31 21:23

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_area_code_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(default=clients.models.generate_unknown_name, max_length=100),
        ),
    ]
