# Generated by Django 5.2.4 on 2025-09-01 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invalid_number',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PhoneNumberClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('area_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Phone Number',
                'verbose_name_plural': 'Client Phone Numbers',
                'unique_together': {('client', 'phone_number')},
            },
        ),
    ]
