# Generated by Django 5.2.4 on 2025-09-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_invalid_number_phonenumberclient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonenumberclient',
            unique_together={('client', 'area_code', 'phone_number')},
        ),
        migrations.AddField(
            model_name='client',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phonenumberclient',
            name='invalid_number',
            field=models.BooleanField(default=False),
        ),
    ]
