# Generated by Django 5.2.4 on 2025-09-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_phonenumberclient_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='invalid_number',
            new_name='invalid_format_number',
        ),
        migrations.RenameField(
            model_name='phonenumberclient',
            old_name='invalid_number',
            new_name='invalid_format_number',
        ),
        migrations.AddField(
            model_name='client',
            name='primary_phone_mismatch',
            field=models.BooleanField(default=False),
        ),
    ]
