# Generated by Django 5.2.4 on 2025-09-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_rename_invalid_number_client_invalid_format_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='invalid_format_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_phone_mismatch',
        ),
        migrations.AddField(
            model_name='client',
            name='primary_phone_match',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='valid_format_number',
            field=models.BooleanField(default=True),
        ),
    ]
