# Generated by Django 5.2.4 on 2025-09-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_client_invalid_format_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumberclient',
            name='invalid_format_number',
        ),
        migrations.AddField(
            model_name='phonenumberclient',
            name='valid_format_number',
            field=models.BooleanField(default=True),
        ),
    ]
