# Generated by Django 5.2.4 on 2025-09-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_phonenumberclient_invalid_format_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='valid_format_number',
        ),
        migrations.RemoveField(
            model_name='phonenumberclient',
            name='valid_format_number',
        ),
        migrations.AddField(
            model_name='client',
            name='phone_format_error',
            field=models.CharField(choices=[('valid', 'Válido'), ('not_numeric', 'No son números'), ('too_long', 'Más de 10 dígitos'), ('too_short', 'Menos de 10 dígitos'), ('starts_plus', 'Comienza por +'), ('special_chars', 'Contiene caracteres especiales'), ('empty', 'Vacío')], default='valid', max_length=20),
        ),
        migrations.AddField(
            model_name='phonenumberclient',
            name='phone_format_error',
            field=models.CharField(choices=[('valid', 'Válido'), ('not_numeric', 'No son números'), ('too_long', 'Más de 10 dígitos'), ('too_short', 'Menos de 10 dígitos'), ('starts_plus', 'Comienza por +'), ('special_chars', 'Contiene caracteres especiales'), ('empty', 'Vacío')], default='valid', max_length=20),
        ),
    ]
