# Generated by Django 5.2.4 on 2025-09-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_client_valid_format_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='original_area_code',
            field=models.CharField(blank=True, help_text='Código de área original para histórico.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='original_phone_number',
            field=models.CharField(blank=True, help_text='Valor original del número para histórico.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phonenumberclient',
            name='original_area_code',
            field=models.CharField(blank=True, help_text='Código de área original para histórico.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='phonenumberclient',
            name='original_phone_number',
            field=models.CharField(blank=True, help_text='Valor original del número para histórico.', max_length=20, null=True),
        ),
    ]
