# Generated by Django 5.2.4 on 2025-09-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_third_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='second_area_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='third_area_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
