# Generated by Django 5.2.4 on 2025-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_second_area_code_client_third_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('consolidated', 'Consolidated'), ('inactive', 'Inactiv'), ('imported', 'Imported'), ('vip', 'VIP')], default='prospect', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_format_error',
            field=models.CharField(choices=[('valid', 'Válido'), ('not_numeric', 'No son números'), ('internacional', 'Número internacional'), ('more_than_one', 'Más de un número'), ('too_long', 'Más de 10 dígitos'), ('too_short', 'Menos de 10 dígitos'), ('starts_plus', 'Comienza por +'), ('special_chars', 'Contiene caracteres especiales'), ('empty', 'Vacío'), ('unknown', 'Desconocido')], default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='phonenumberclient',
            name='phone_format_error',
            field=models.CharField(choices=[('valid', 'Válido'), ('not_numeric', 'No son números'), ('internacional', 'Número internacional'), ('more_than_one', 'Más de un número'), ('too_long', 'Más de 10 dígitos'), ('too_short', 'Menos de 10 dígitos'), ('starts_plus', 'Comienza por +'), ('special_chars', 'Contiene caracteres especiales'), ('empty', 'Vacío'), ('unknown', 'Desconocido')], default='valid', max_length=20),
        ),
    ]
