# Generated by Django 5.2.4 on 2025-12-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='original_phone_number',
            field=models.CharField(blank=True, help_text='Valor original del número para histórico.', max_length=100, null=True),
        ),
    ]
