# Generated by Django 5.2.4 on 2025-12-21 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('notifications_scheduler', '0014_scheduledmessage_replace_text_message_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='scheduled_message_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='notifications_scheduler.clientscheduledmessage'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Programada'), ('COMPLETED', 'Completada'), ('RESCHEDULED', 'Reprogramada'), ('CLOSED', 'Cerrada'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'No Asistió')], default='SCHEDULED', max_length=20),
        ),
    ]
