# Generated by Django 5.2.4 on 2025-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='service_types',
            field=models.ManyToManyField(blank=True, help_text='Tipos de servicio que puede realizar la operaria', related_name='operators', to='sales.servicetype'),
        ),
    ]
